---
title: "Stripe MRR Forecasts"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(scales)
library(lubridate)

# access helper functions
source("mrr_source.R")

# get end of month
eom <- Sys.Date()
day(eom) <- days_in_month(eom)

# get end of last month
last_month <- eom %m-% months(1)

# get mrr data 
mrr <- get_mrr_data() 

# get publish forecasts
publish_fc <- get_forecast(mrr, application = "publish")

# get reply forecasts
reply_fc <- get_forecast(mrr, application = "reply")

# get analyze forecasts
analyze_fc <- get_forecast(mrr, application = "analyze")

# get end of month forecasts
publish_eom_forecast <- get_eom_value(publish_fc, eom)
reply_eom_forecast <- get_eom_value(reply_fc, eom)
analyze_eom_forecast <- get_eom_value(analyze_fc, eom)

# get projected growth rates
publish_gr <- get_growth_rate(publish_fc, eom, last_month)
reply_gr <- get_growth_rate(reply_fc, eom, last_month)
analyze_gr <- get_growth_rate(analyze_fc, eom, last_month)
```

All of Buffer
=======================================================================

Row
-----------------------------------------------------------------------

### Publish End of Month Forecast

```{r}
# publish forecast
renderValueBox({
  valueBox(
    value = publish_eom_forecast,
    icon = "fa-bars"
  )
})
```

### Reply End of Month Forecast

```{r}
# reply forecast
renderValueBox({
  valueBox(
    value = reply_eom_forecast,
    icon = "fa-exchange-alt"
  )
})
```

### Analyze End of Month Forecast

```{r}
# analyze forecast
renderValueBox({
  valueBox(
    value = analyze_eom_forecast,
    icon = "fa-chart-line"
  )
})
```

Row
-----------------------------------------------------------------------

### Publish Projected Growth Rate

```{r}
# publish forecast
renderValueBox({
  valueBox(
    value = percent(publish_gr),
    icon = "fa-bars",
    color = ifelse(publish_gr > 0.01, "success",
                   ifelse(publish_gr > 0.005, "warning", "danger"))
  )
})
```

### Reply Projected Growth Rate

```{r}
# reply forecast
renderValueBox({
  valueBox(
    value = percent(reply_gr),
    icon = "fa-exchange-alt",
    color = ifelse(reply_gr > 0.05, "success",
                   ifelse(reply_gr > 0.03, "warning", "danger"))
  )
})
```

### Analyze Projected Growth Rate

```{r}
# analyze forecast
renderValueBox({
  valueBox(
    value = percent(analyze_gr),
    icon = "fa-chart-line",
    color = ifelse(analyze_gr > 0.4, "success",
                   ifelse(analyze_gr > 0.2, "warning", "danger"))
  )
})
```

Row
-----------------------------------------------------------------------

### Publish Forecast

```{r}
# publish forecast plot
renderPlotly({

  pub_fc <- mrr %>% 
    filter(simplified_plan_id != 'reply' & simplified_plan_id != 'analyze') %>% 
    group_by(date) %>% 
    summarise(mrr = sum(mrr, na.rm = TRUE)) %>% 
    rename(point_forecast = mrr) %>% 
    get_forecast_obj()
  
  p <- ggplot() +
    geom_line(data = publish_fc, aes(x = forecast_at, y = forecasted_mrr_value)) +
    geom_line(data = pub_fc, aes(x = date, y = point_forecast), color = 'blue') +
    geom_ribbon(data = pub_fc, aes(x = date, ymin = lo_95, ymax = hi_95), fill = "grey70", alpha = 0.8) +
    scale_y_continuous(labels = dollar) +
    labs(x = NULL, y = NULL, title = NULL)
  
  ggplotly(p) 
  
})
```

### Reply Forecast

```{r}
# publish forecast plot
renderPlotly({

  rep_fc <- mrr %>% 
    filter(simplified_plan_id == 'reply') %>% 
    group_by(date) %>% 
    summarise(mrr = sum(mrr, na.rm = TRUE)) %>% 
    rename(point_forecast = mrr) %>% 
    get_forecast_obj()
  
  p <- ggplot() +
    geom_line(data = reply_fc, aes(x = forecast_at, y = forecasted_mrr_value)) +
    geom_line(data = rep_fc, aes(x = date, y = point_forecast), color = 'blue') +
    geom_ribbon(data = rep_fc, aes(x = date, ymin = lo_95, ymax = hi_95), fill = "grey70", alpha = 0.8) +
    scale_y_continuous(labels = dollar) +
    labs(x = NULL, y = NULL, title = NULL)
  
  ggplotly(p) 
  
})
```

### Analyze Forecast

```{r}
# publish forecast plot
renderPlotly({

  ana_fc <- mrr %>% 
    filter(simplified_plan_id == 'analyze') %>% 
    group_by(date) %>% 
    summarise(mrr = sum(mrr, na.rm = TRUE)) %>% 
    rename(point_forecast = mrr) %>% 
    get_forecast_obj()
  
  p <- ggplot() +
    geom_line(data = analyze_fc, aes(x = forecast_at, y = forecasted_mrr_value)) +
    geom_line(data = ana_fc, aes(x = date, y = point_forecast), color = 'blue') +
    geom_ribbon(data = ana_fc, aes(x = date, ymin = lo_95, ymax = hi_95), fill = "grey70", alpha = 0.8) +
    scale_y_continuous(labels = dollar) +
    labs(x = NULL, y = NULL, title = NULL)
  
  ggplotly(p) 
  
})
```


Analyze
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

Select the Analyze plans to include in the forecasts. 

```{r}
selectInput(inputId = "analyze_plans", 
            label = "Analyze plans",
            multiple = TRUE,
            choices = c("analyze-early-access-10-profiles",
                        "analyze-early-access-25-profiles",
                        "analyze-early-access-50-profiles",
                        "analyze-early-access-100-profiles",
                        "analyze-early-access-10-profiles-annual",
                        "analyze-early-access-200-profiles"), 
            selected = c("analyze-early-access-10-profiles",
                        "analyze-early-access-25-profiles",
                        "analyze-early-access-50-profiles",
                        "analyze-early-access-100-profiles",
                        "analyze-early-access-10-profiles-annual",
                        "analyze-early-access-200-profiles"))
```

Row
-----------------------------------------------------------------------

### Analyze End of Month Forecast

```{r}
# analyze forecast
renderValueBox({
  
  # get analyze forecasts
  analyze_fc <- mrr %>% 
    filter(plan_id %in% input$analyze_plans) %>% 
    get_forecast(application = "analyze")

  # get end of month forecasts
  analyze_eom_forecast <- get_eom_value(analyze_fc, eom)
  
  valueBox(
    value = analyze_eom_forecast,
    icon = "fa-chart-line"
  )
})
```

### Analyze Projected EoM Growth Rate

```{r}
# analyze forecast
renderValueBox({
  
  # get analyze forecasts
  analyze_fc <- mrr %>% 
    filter(plan_id %in% input$analyze_plans) %>% 
    get_forecast(application = "analyze")
  
  # get projected growth rate
  analyze_gr <- get_growth_rate(analyze_fc, eom, last_month)
  
  valueBox(
    value = percent(analyze_gr),
    icon = "fa-chart-line",
    color = ifelse(analyze_gr > 0.4, "success", ifelse(analyze_gr > 0.2, "warning", "danger"))
  )
})
```

Row
-----------------------------------------------------------------------

### Analyze Revenue Forecasts

```{r}
# publish forecast plot
renderPlotly({

  analyze_fc <- mrr %>% 
    filter(plan_id %in% input$analyze_plans) %>% 
    get_forecast(application = "analyze")
    
  analyze_fc_object <- mrr %>% 
    filter(plan_id %in% input$analyze_plans) %>% 
    group_by(date) %>% 
    summarise(mrr = sum(mrr, na.rm = TRUE)) %>% 
    rename(point_forecast = mrr) %>% 
    get_forecast_obj()
  
  p <- ggplot() +
    geom_line(data = analyze_fc, aes(x = forecast_at, y = forecasted_mrr_value)) +
    geom_line(data = analyze_fc_object, aes(x = date, y = point_forecast), color = 'blue') +
    geom_ribbon(data = analyze_fc_object, aes(x = date, ymin = lo_95, ymax = hi_95), fill = "grey70", alpha = 0.8) +
    scale_y_continuous(labels = dollar) +
    labs(x = NULL, y = NULL, title = NULL)
  
  ggplotly(p) 
  
})
```
